### ISSUE TITLE
[PENDING] [COCOAPODS] build error on ios

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GMEXT-Firebase#9]
when build on mac

gms2 23.4.0.84 version : build success 

but

gms2 23.8.1 version   :   firebasecore.h not found...

**Comment by DiasFranciscoA** [comment]
Hello @searoopy,

Thank you for bringing this to our attention. In order to assist you more effectively, we'll need some additional information.

Please provide the output log from your console. This will offer us deeper insight into the exact nature of the problem. If you're utilizing the new IDE, you might consider filing the bug directly from within its form. Doing so will automatically attach all the necessary details which would be highly beneficial for our troubleshooting.

Additionally, it would be helpful if you could run the firebase project specifically targeting iOS. Once it encounters the error, immediately file the bug so that the pertinent information is captured and appended to your report.

We appreciate your cooperation and patience as we work to resolve this issue.

**Comment by DiasFranciscoA** [comment]
We are waiting for information on this, this issues was stale for too long.
If the problem persists please reopen the ticket.
